title: The blog of Anatolii Kmetiuk
description: The blog of Anatolii Kmetiuk
locale: en-GB
keywords: [scala,programming,functional programming,category theory,kmetiuk,kmetyuk,anatolii kmetiuk,anatoliy kmetyuk]