# General Jekyll Config
highlighter: rouge
url: http://akmetiuk.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

paginate: 25

destination: ../out

markdown: Pandoc
pandoc:
  extensions:
    - webtex
    - toc
    - standalone
    - highlight-style: pygments
    - filter: _pandoc/pandocfilters/examples/graphviz.py
    - filter: _pandoc/pandoc-plantuml-filter/dist/build/pandoc-plantuml-filter/pandoc-plantuml-filter
    - filter: _pandoc/pandoc-include-code/dist/build/pandoc-include-code/pandoc-include-code

# kramdown:
#   input: GFM
#   syntax_highlighter: rouge
# redcarpet:
#   extensions: ["strikethrough"]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll_github_sample
  - jekyll-plantuml
  - jekyll-paginate
  - jekyll-pandoc
