# General Jekyll Config
highlighter: rouge
url: http://akmetiuk.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

paginate: 25

destination: ../out

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
# redcarpet:
#   extensions: ["strikethrough"]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll_github_sample
  - jekyll-plantuml